Update Build_SukiSU_All_V2.yml

diff --git a/.github/workflows/Build_SukiSU_All_V2.yml b/.github/workflows/Build_SukiSU_All_V2.yml
--- a/.github/workflows/Build_SukiSU_All_V2.yml
+++ b/.github/workflows/Build_SukiSU_All_V2.yml
@@ -217,21 +217,21 @@ jobs:
           rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
           rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"          
           
-      - name: Inline walt scheduler
-        run: |
-          if [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.6" ]; then
-          cd kernel_workspace/kernel_platform
-          CONFIG_FILE=./common/arch/arm64/configs/gki_defconfig
+          if [ -f "$CONFIG_FILE" ]; then
           echo "CONFIG_SCHED_WALT=y" >> "$CONFIG_FILE"
           echo "CONFIG_SCHED_WALT_DEBUG=y" >> "$CONFIG_FILE"
+          else
+          echo "Error: $CONFIG_FILE not found"
+          exit 1
+          fi
                                         
       - name: Add fengchi
         run: |
           if [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.6" ]; then
           cd kernel_workspace/kernel_platform/common
-          # wget https://github.com/reigade-gr/Action-Build/raw/gki_official/fengchi.patch
           git apply fengchi.patch
           echo "Fengchi added successfully"
+          fi
           
       - name: Force remove -dirty suffix
         run: |
