Update Suki.yml

diff --git a/.github/workflows/Suki.yml b/.github/workflows/Suki.yml
--- a/.github/workflows/Suki.yml
+++ b/.github/workflows/Suki.yml
@@ -445,14 +445,17 @@ jobs:
       # Set build timestamp
       - name: scx
         run: |
-          cd kernel_workspace/common
-            wget https://raw.githubusercontent.com/cctv18/kernel_common_oplus_sm8650_scx/refs/heads/main/sched_ext.patch
-            patch -p1 -F 5 < sched_ext.patch || true
-              cd drivers
-              wget https://raw.githubusercontent.com/cctv18/kernel_common_oplus_sm8650_scx/refs/heads/main/hmpatch.c
-              if ! grep -q "hmpatch.o" Makefile; then
-                echo "obj-y += hmpatch.o" >> Makefile
-              fi
+          cd kernel_workspace/kernel_platform/common
+          wget https://raw.githubusercontent.com/cctv18/kernel_common_oplus_sm8650_scx/refs/heads/main/sched_ext.patch
+          if ! patch -p1 -F 5 < sched_ext.patch; then
+            echo "::error::Failed to apply sched_ext.patch"
+            exit 1
+          fi
+          cd drivers
+          wget https://raw.githubusercontent.com/cctv18/kernel_common_oplus_sm8650_scx/refs/heads/main/hmpatch.c
+          if ! grep -q "hmpatch.o" Makefile; then
+            echo "obj-y += hmpatch.o" >> Makefile
+          fi
                 
       - name: Set Kernel build timestamp
         run: |
